### ISSUE TITLE
 Is flask-vuejs only for python 3.8 version?

### ISSUE THREAD

**Issue by MrMindy** [marcuxyz/flask-vuejs#10]
Hey, what's up Marcus? Is everything allright? Dude, I was watching your live about some minutes ago and I've tried to install flask-vuejs using Python 3.7.6 and the pip didn't found the library. It said: 

**> Python 3.7.6**

**> ERROR: Could not find a version that satisfies the requirement flask-vuejs (from versions: none)** 

**> ERROR: No matching distribution found for flask-vuejs**

So my question is:  Is flask-vuejs only for python 3.8 version? I've tried with python 3.8 version and worked smoothly.  If that is the case, I trully recommend to update your docs, at least on http://flaskvue.pacotei.xyz/, there's no mention about it.

**Comment by marcuxyz** [comment]
Hello, @MrMindy thanks for your report. If you look at the `CI` you’ll realize that it really shouldn’t happen, See:

https://github.com/pacotei/flask-vuejs/runs/562687182

**I fix this.**

**Comment by marcuxyz** [comment]
this has been fixed. Thanks again @MrMindy  but, now, use the `flask-vuejs` on 3.6+ version of python
